FROM python:3.12-slim
WORKDIR /backend
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 10000
CMD ["waitress-serve", "--listen=0.0.0.0:$PORT", "backend:create_app"]
